app_password_auth/urls.py
from django.urls import path
from app_password_auth import views
#from django.contrib import admin

app_name = 'app_password_auth'

urlpatterns = [
    path('register/',views.register,name='view_register'),
    path('user_login/',views.user_login,name='view_user_login'),

]

project_password_encryption/urls.py
from django.contrib import admin
from django.urls import include, path
from app_password_auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_password_auth/', include('app_password_auth.urls')),
    path('', views.index, name='index'),
    path('logout/',views.user_logout,name='logout'),
    path('view_special/',views.special,name='view_special'),

]

app_password_auth/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

"""
The django already have provided default User which has in built attributes username, firstName, lastname, email and password.
In addition to these attributes we also need other attributes such as users' own portfolio site or users'own profile picture etc.
Hence we are creating an object called end_user which will have one-one relationship to the in-built User.
"""
class EndUserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    ## Additional attributes
    end_user_site = models.URLField(blank=True)
    # to use image field install pillow libraries
    # display_pics is the folder name which is in media folder and we have set the path and tagged to MEDIA_ROOT in settings.py file
    end_user_dp = models.ImageField(blank=True, upload_to = 'display_pics' )

    def __str__(this):
        # we are returning default username that comes with django
        return this.user.username

app_password_auth/forms.py
from django import forms
from app_password_auth.models import EndUserProfileInfo
from django.contrib.auth.models import User

class CustomUserForm(forms.ModelForm):
    class Meta():
        # Never use () to call EndUserProfileInfo
        model = EndUserProfileInfo
        # fields = '__all__'
        fields = ('end_user_site','end_user_dp')



class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email',)

app_password_auth/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import CustomUserForm, UserForm
# Create your views here.
# Libraries for django Login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

@login_required
def user_logout(request):
     logout(request)
     return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
     return HttpResponse('You are logged in')

def index(request):
    return render(request,'app_password_auth/index.html')


def register(request):
    registered = False
    if request.method == 'POST':
        fu = UserForm(data = request.POST)
        fcu = CustomUserForm(data = request.POST)


        if fu.is_valid() and fcu.is_valid():
            user = fu.save()
            user.set_password(user.password)
            user.save()

            profile = fcu.save(commit=False)

            """
            profile is an instance of fcu.
            fcu is an instance of CustomUserForm.
            CustomUserForm is configured to the model of EndUserProfileInfo.
            EndUserProfileInfo class has end_user = models.OneToOneField(User, on_delete = models.CASCADE)
            """
            profile.user = user

            if 'end_user_dp' in request.FILES:

                """
                request.FILES is USED FOR ALL UPLOADED FILES LIKE .CSV .TXT .JPEG .PNG etc.
                """
                profile.end_user_dp = request.FILES['end_user_dp']

            profile.save()
            registered = True
        else:
            print(fu.errors, fcu.errors)
    else:
        fu = UserForm()
        fcu = CustomUserForm()

    return render(request, 'app_password_auth/registration_page.html', {'user_form':fu, 'user_profile_form':fcu, 'registered':registered})

# Do not use class name as login as we already have imported login form django.contrib.auth
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password =  request.POST.get('password')

        # the django function will authenticate the user
        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                # use the login function which you have imported from django
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("User is not activated")
        else:
            print("The username {} with password {} tried to login".format(username, password))
            return HttpResponse("User authentication failed")
    else:
        return render(request, 'app_password_auth/user_login.html', {})

templates/app_password_auth/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>The Base HTML</title>
    <link rel="stylesheet" href="{% static "/css/Capston.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="nav navbar-default navbar-fixed-top navbar-inverse">

        <div class="navbar-header">
          <!-- <li><a class="navbar-brand" href="#">BRAND</a></li>
          <li><a class="navbar-link" href="#">Admin</a></li>
          <li><a class="navbar-link" href="#">Other</a></li> -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <!--  Code for the hamburger icon-->
            <span class="sr-only">Toggle navigation</span>
            <!--code for dashes in hamburger-->
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- index is the name for idnex page which we have defined in the project's url.py file -->
          <a class="navbar-brand" href="{% url 'index' %}">Welcome</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a class="navbar-link" href="{% url 'index' %}">Brand</a></li> <!-- index is the name we defined in the projects urls.py file -->
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <!-- app_password_auth is the app_name which we registred in our apps ulrs.py script -->
            <!-- view_register is a name which we have defined in apps urls.py script  -->
            <li><a class="navbar-link" href="{% url 'app_password_auth:view_register' %}">Register User</a></li>
            <!-- If the user is authenticated then user will need a way to logout -->
            {% if user.is_authenticated %}
              <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li><!--logout is the name we defined in the projects urls.py file -->
            {% else %}
              <li><a class="navbar-link" href="{% url 'app_password_auth:view_user_login' %}">Login User</a></li>
            {% endif %}
            <li><a class="navbar-link" href="{% url 'view_special' %}">Special View</a></li>
          </ul>
        </div>

    </nav>

        <div class="container">
          {% block body_block %}
          <!-- code for other html files which all will inherit this base.html file -->
          {% endblock %}
        </div>

        <script
       src="http://code.jquery.com/jquery-3.1.1.js"
       integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
       crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
       <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  </body>
</html>

templates/app_password_auth/index.html
<!DOCTYPE html>
{% extends "app_password_auth/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h2>Django level 5</h2>
  </div>
{% endblock %}

templates/app_password_auth/registration_page.html
<!DOCTYPE html>
{% extends "app_password_auth/base.html" %}
{% load static %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h5>Thank You for regestering!</h5>
    {% else %}
      <h5>Register Here</h5>
      <h5>Fill out the form:</h5>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ user_profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>
{% endblock %}

templates/app_password_auth/user_login.html
<!DOCTYPE html>
{% extends "app_password_auth/base.html" %}
{% load static %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">
      <h2>Please Login</h2>
      <form action="{% url 'app_password_auth:view_user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Provide Username">

        <label for="password">Password</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
      </form>
    </div>
  </div>

{% endblock %}